import { Container } from "@chakra-ui/react";
import { Navbar, Hero } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" mt={10}>
        <Navbar />
        <Hero />
      </Container>
    </>
  );
}
